baseURL = 'https://djsamsam.github.io/samscorner/'
languageCode = 'en-us'
title = 'Sam´s corner'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

      [markup.goldmark.parser.attribute]
        block = true

    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        useEmbedded = "fallback"

      [markup.goldmark.renderHooks.image]
        useEmbedded = "fallback"

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    source = 'static'
    target = 'assets'

[permalinks]
  blog = "/:title/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 20


  [[menu.main]]
    identifier = "youtube"
    name = "My Youtube Channel"
    url = "https://www.youtube.com/channel/UCU6bOWsqx_SeUl9UEJPIw-w"
    weight = 25

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "guestbook"
    name = "Guestbook"
    url = "/guestbook/"
    weight = 40